#! /bin/sh

# this is a small SH script which will spawn vim as your pager. It does wonders
# for man pages. And looks cool too.
# Just chmod this script for execute and export the environment veriable PAGER
# to point to this file.
#       PAGER=$HOME/bin/pager; export PAGER

if test x$1 == x; then
    cat $1 | col -b | view \
    -c 'set foldcolumn=0' \
    -c 'set nonumber' \
    -c 'set nolist' \
    -c 'filetype detect' \
    -
else
    view \
    -c 'set foldcolumn=0' \
    -c 'set nonumber' \
    -c 'set nolist' \
    -c 'filetype detect' \
    "$@"
fi
